# Generated by Django 4.0.4 on 2022-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
    ]
