# Generated by Django 4.0.4 on 2022-05-28 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 12, 46, 14, 832564, tzinfo=utc)),
        ),
    ]
