# Generated by Django 4.0.4 on 2022-05-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
    ]
