# Generated by Django 4.0.4 on 2022-06-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_name_alter_comment_commenter_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieLinks',
            new_name='MovieLink',
        ),
    ]
