# Generated by Django 4.0.5 on 2022-06-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_rename_movielinks_movielink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='post',
        ),
    ]
