# Generated by Django 4.0.4 on 2022-05-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_movie_banner_movie_created_movie_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
    ]
