# Generated by Django 4.0.4 on 2022-06-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_comment_options_rename_body_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.movie'),
            preserve_default=False,
        ),
    ]
