# Generated by Django 4.0.4 on 2022-05-28 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_movie_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 5, 28), null=True),
        ),
    ]
