# Generated by Django 4.0.4 on 2022-06-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_comment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
    ]
