# Generated by Django 4.0.4 on 2022-05-28 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_movie_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 28, 16, 34, 43, 983381, tzinfo=utc), null=True),
        ),
    ]
